from flet import colors
APP_BG = colors.DEEP_ORANGE_400
BOTTOM_BAR = colors.GREEN
MAIN_COLOR_1 = colors.GREEN_800
MAIN_COLOR_2 = colors.LIGHT_GREEN_900

CURRENT_SET_COLOR_1 = colors.LIGHT_GREEN
CURRENT_SET_COLOR_2 = colors.GREEN

CURRENT_GAME_COLOR_1 = colors.WHITE
CURRENT_GAME_COLOR_2 = colors.GREY_400

SCOREBOARD_TEXT_SIZE = 20
SCOREBOARD_PLAYER_SIZE = 16